### ISSUE TITLE
Submit to GPlay, F-Droid, &c

### ISSUE THREAD

**Issue by TPS** [Willena/OpenDNSUpdater#1]
@Willena Are you still working on this?  If so, I'd appreciate if you could put together a recent APK on your `/releases` (to avoid looking abandoned) & give me an ok to [RFP on F-Droid](https://gitlab.com/fdroid/rfp) or @Izzysoft's [repo](https://apt.izzysoft.de/fdroid/index/info).

**Comment by Willena** [comment]
@TPS First, I'm impress that you're interested in this small "not finished" project. 
I'll be honest with you, I don't know what's F-Droid and this project is quite old now. The last commit was pushed almost three years ago, and version of Android have changed a lot. Updating this project, is not impossible but I dont have the time for the moment to do these kind of things. 
But if you 're really interested, I can add this project onto my todo list.

In the past, I have thought about putting it on Google Play, but as you see the app is not "ready" for that. It was at the time a solution to a personal problem. 

Again, if you're interested, I can make some changes, but I think you may have to be patient.

Thanks.

**Comment by IzzySoft** [comment]
@TPS I'd gladly take it into my repo until it makes its way into the official one – but as @Willena correctly points out this doesn't make sense for a project not being updated for 3 years and (no offense meant) obviously no longer maintained.

**Comment by Willena** [comment]
@IzzySoft You're absolutely right ! In fact I almost had forgotten it. ~~Moreover, I don't know if OpenDNS still provide APIs and the service I've used.~~ (I've just checked: services and APIs seems to be active and working as used in the project)

**Comment by IzzySoft** [comment]
@Willena just ping me if the need arises. As I wrote, I'll glady add your app to my repo – and assist if you want to make for the official one.

**Comment by TPS** [comment]
@Willena There _is_ a need for it, as your app seems to be the ___only___ 1 on Android that does precisely this, so I'd appreciate any love you give this anytime you wish to.

[F-Droid, in short, is an _alternative_ app "store" tailor-made for open-source Android software.](https://f-droid.org/en/about/)  If you use Android, check it out.

@IzzySoft I'm thankful for your interest in what seems to be a unique solution to a niche service, as large as it is.

**Comment by IzzySoft** [comment]
@Willena a short and incomplete summary of what I find important about F-Droid:

* privacy friendly. You can use it without accout, no data collected
* offline. Like with Debian, you download the index; all interaction (searches, what apps you take a closer look at) happens on your device. No profiling.
* FOSS. All apps have been checked. I can trust they have no trackers or other "bad stuff".

Apart from the main repo (to which the above applies), the user can pick additional ones (think of "Ubuntu PPAs") – like mine. The first two bullet points always apply. With those "additional repos" you just cannot be sure about the 3rd. So with my repo, I always recommend taking a look with the browser to clarify that. The web presence e.g. points out what libraries are used in an app – something that, unfortunately, doesn't make it into the F-Droid client. While rules are very strict about what goes into the official repo, for mine rules are a bit relaxed; mainly to give devs a chance to get their apps ready for the official repo, while still being available via the client.

Of course, users will be notified about app updates and can apply them. And apps are easier found as you have some "index" to look into (opposed to crawling through all kind of sites like Github, GitLab and others for a "hopeful find").

So if you are continuing your app (which we would very much welcome), please consider our repos :wink:

**Comment by TPS** [comment]
>And apps are easier found as you have some "index" to look into (opposed to crawling through all kind of sites like Github, GitLab and others for a "hopeful find").

&/or relying upon the mystic Google-fu, which is how I chanced upon this repo! 🍀

**Comment by Willena** [comment]
@TPS Challenge accepted ! I will try to work on the app during the summer in order to refresh it a bit 

@IzzySoft @TPS I think I will also post it on Google Play. But your repo seems interesting. 

@IzzySoft Thanks for all these information about F-droid. I did know about it before. You make me learn something today, Thanks ! 👍

**Comment by IzzySoft** [comment]
@Willena Yay! That's great news. And yes, F-Droid should be something a privacy-oriented FOSS developer should know about :stuck_out_tongue_winking_eye: Some folks (like me) strongly prefer F-Droid over any proprietary store (I only use apps from Play if there's no suitable alternative on F-Droid *and I cannot do without,* and then usually not with their app but Yalp/Raccoon/Aurora), others don't use Playstore/Amazon/<you-name-it> at all. So we're excited you consider it for your app, and look forward to that day!

@TPS I also have my own Github search engine, which filters out 90% of what I'm not interested in. Use that to find food for my repo. But with MS having acquired¹ Github I'm not sure how long I will stay here. I don't want to feed another data leech.

¹ <sub>rumors have it MS is about to buy a vacuum cleaner company next. That will be the first MS product which doesn't suck…</sub>

**Comment by TPS** [comment]
@Willena I didn't mean to _challenge_ you (in the negative sense), but I sincerely do love __encouraging__ the unique ___&___ useful, in which category this app falls ☐ly.

@IzzySoft I'm hoping @Microsoft is desperate enough to try something new: leave a successful business model alone, other than [_increasing_ its similarity to GitLab re: privacy, openness, & responsiveness](https://about.gitlab.com/2018/06/03/microsoft-acquires-github/).

**Comment by Willena** [comment]
@TPS no problem. I understand. I will update the app and let you know when ready.
@IzzySoft I can understand your point of view on proprietary apps and stores. But when this app will be rewritten, I think I will post it on Google Play, but also on your repo. 

Thanks for your intrest ! I'll ping both of you when the app will be ready.

**Comment by TPS** [comment]
@Willena I meant to mention earlier: If you need end-user/β-testing/feedback/whatever @ _any (or every 😉)_ point, I'd be more than happy to do so.  Just ping! 😀 :bow:

**Comment by TPS** [comment]
@IzzySoft: @Willena has changed the package name from `net.dgistudio.guillaume.opendnsupdater` → `villena.guillaume.fr.opendnsupdater` @ https://github.com/Willena/OpenDNSUpdater/commit/475c65fab0a4750155b7515fbd75d5ec830e93af which may impact your repo whenever there's the next release (though I think you haven't put it in yet).

**Comment by IzzySoft** [comment]
@TPS Thanks for the info – and no, I haven't yet. Was waiting for a fresh release :wink:

**Comment by Willena** [comment]
Yeah, it is recommended to wait for an "official" release. I just started to recreate the application.

**Comment by TPS** [comment]
@Willena I just wanted to check in to find out whether there's anything I could do as an enduser to help you.  I still run your original release version constantly.

**Comment by Willena** [comment]
@TPS for the moment I don't have the time to continue this development... I think I'll be able to restart working on it next month or later.

**Comment by Willena** [comment]
Submitted to Google Play : version 2.0.1 => https://play.google.com/store/apps/details?id=fr.guillaumevillena.opendnsupdater

**Comment by IzzySoft** [comment]
Thanks a lot! Any plans for a license? :wink:

Added it to [my repo](https://apt.izzysoft.de/fdroid/repo) just now. But ony hesitatingly, as it comes with a lot of trackers. Could you please provide an APK that comes without Crashlytics and Firebase? Also, what is GMS needed for?

Further, I had to add the NonFreeNet AntiFeature. The service might be free as in "free speech", but as far as I can see not as in "free speech".

**Comment by Willena** [comment]
@IzzySoft I don't have any plan concerning the license. In fact I don't realy know witch one I should choose.

Yes, Crashlytics and Firebase can be removed. But they are incredible tool to debug and have crash report as a developer. If your concerns are about crash report that are sent without your consent, I think I can add a popup to ask if you would like to send the crash report.

GooglePlayServices or GMS as you call them, are used in collaboration with JobDispatcher that allow the app to listen "correctly" to some network events. Things have changed in recent android APIs (see : https://stackoverflow.com/questions/46163131/android-o-detect-connectivity-change-in-background). To be able to receive these events I'm using https://github.com/firebase/firebase-jobdispatcher-android#requirements.

I'm not sure to understand your last sentence, can you give me more details ? 

> Further, I had to add the NonFreeNet AntiFeature. The service might be free as in "free speech", but as far as I can see not as in "free speech".

**Comment by IzzySoft** [comment]
Not having a license is a show-stopper for the official repo – but so are Crashlytics and Firebase. And no, I have no concerns *you* would abuse them – but the two are calling home to Google, which you hardly can be sure to disable considering their closed-source nature. If you really need some Analytics, consider ACRA or Matomo with a self-hosted instance. Both would even be acceptable for F-Droid AFAIK (I'm sure about ACRA at least).

GMS (Google Mobile Services) – yes, `c2dm.permission.RECEIVE` already pointed to that. Another show-stopper for the official repo (though not for mine). I wasn't aware what for it would be *required* here. Isn't there an open connection anyway, so it could be used directly? If really needed, Tutanota has implemented an alternative into their app. Should be worth a look.

One thing at a time, of course – and the trackers of the first paragraph should go first IMHO :wink:

NonFreeNet: Is the service Open Source, so you could self-host it if you wished (which would be "FreeNet") – or is your app "useless" when opendns.com shuts down (which makes it NonFreeNet)?

**Comment by Willena** [comment]
Ok, I understand. I'll try to think of a license and will remove Crashlytics and Firebase. I'll try to replace the current JobDispatcher (it will remove GplayServices) to something else. 

>  Isn't there an open connection anyway,

Just to be clear. By network event I mean when you switch from wifi to mobile data for example. It is not for event linked with HTTP requests. More with the physical state on the device.

Thanks for the NonFreeNet definition. Of course this app rely on OpenDNS.com and therefore cannot be FreeNet, but the app can easily be adapted if another service have such filter available.

**Comment by IzzySoft** [comment]
> I'll try to think of a license and will remove Crashlytics and Firebase.

Great! And very much appreciated!!!

[Network Event / GMS]

Looks like I get confused by the name of the app (DNSUpdater sounds like an app to update the dynamic IP, like DynDNS) and the description ("This type of service is free and can be very usefull to filter websites such as porn, phishing, malware, and many other category." which sounds like a "filtering VPN") – and in the end it is rather DNS lookup? If you meant local network events (as described with your last comment by "you switch from wifi to mobile data"), I don't see why Cloud Messaging (GCM) should be useful … But never mind my "confused brain": if you remove GMS anyway, we don't need to dig deeper into this :rofl:

[NonFreeNet]

Good to hear it should be easy to adapt to another service – makes it easier should the case come up. Still, at this time… well, don't get confused by the term "Open" in "OpenDNS". There's an "open" in "OpenWeatherMap" as well, and it's NonFreeNet nevertheless (just discussed at F-Droid).

Thanks a lot for your open mind and helpfulness! Many of us "tin foils" (and more) will profit from this. Looking forward to the real free version. My updater will inform me when I have to drop the "Tracking" AntiFeature then.

**Comment by Willena** [comment]
[Network Event / GMS]

Well I am confusing you even worst than before... This app is basically an Ip Updater for OpenDNS service. In the readme I am saying that their service is interesting to filter website just using DNS queries. 
In fact the "new" app includes a VPNService that if enable forces the use of OpenDNS DNS servers.
The reason the app needs to listen to android event such as "CONNECTIVITY_CHANGE" is that when the connectivity changes the ip should be updated (usually you change to a different network such as mobile ISP, Wifi ISP, ...). But as you said, GMS will go away anyways.

[NonFreeNet]

The only needed updates to the code to adapt to another service ( or a custom one ) would be to change API calls and interpret the result correctly.

**Comment by IzzySoft** [comment]
Ugh… OK. If you think the app description needs an update, let me know…

And yes, that sould be it – always good to put such calls into a separate class :wink:

**Comment by TPS** [comment]
> I don't have any plan concerning the license. In fact I don't realy know witch one I should choose.

@Willena GitHub's own https://ChooseALicense.Com is a good, simple resource.  N.B.:  When you have dependencies, the license you choose has to be compatible w/ theirs, too.

**Comment by IzzySoft** [comment]
@TPS it's a bit shourt, though – but a good start indeed. @Willena take a closer look at their "NoLicense" (ie. what it means if you don't chose one), certainly not what you want :) So if you cannot settle with one of TPS's list, [find here](https://spdx.org/licenses/) a list of licenses accepted by F-Droid (first table on that page).

**Comment by IzzySoft** [comment]
Hey @Willena, that last release looks very good! Just removed all AntiFeatures from Metadata. And a real license, wow! Let me know when you want to go for the official repo and need my help.

Congrats!

**Comment by Willena** [comment]
@IzzySoft, Thanks ! Happy to hear that ! But I've found little issues on older Android API between ( API 14 to 20 to be precise). I'll inform you when ready. 
One question : Are you updating manually the app version on your repo (or FDroid ) ?

**Comment by IzzySoft** [comment]
Yes, please do! And: Yes, I do (update). Or rather my updater does when triggered by cron. Should happen within 24h of your attaching the APK to a new tag/release. And then is announced in the `#fdroid` channel on Freenode. So "I do update" = yes, but "manually" = no :wink:

**Comment by TPS** [comment]
@Willena Did I miss this being included in the main F-Droid repo, or are you content w/ @IzzySoft's repo?

**Comment by Willena** [comment]
@TPS, @IzzySoft,
I completely forgot about that. I reopen the issue now ! 
I've posted a request here: https://gitlab.com/fdroid/rfp/issues/994

**Comment by IzzySoft** [comment]
Thanks @Willena! Let's wait for the bot over there, then I'll prepare metadata (can copy-paste most of the things from my repo).

Would you mind setting up Fastlane or Triple-T with some screenshots (see e.g. [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) for details)? You could even manage summary and description that way yourself, and F-Droid would pick it up. Makes it easier to get changes applied. And if you wish, you could also use localized descriptions that way. Add the per-release changelogs (`<verCode>.txt`), and it would bring your app to the main screen of the F-Droid client :smiley:

Those steps are not mandatory, but highly recommended. Besides: Did you get rid of Firebase (or have a FOSS flavor without it)? That could be a show-stopper otherwise. According to my library scanner, the last version still comes with Firebase Job Dispatcher and Bugsnag.

**Comment by Willena** [comment]
@IzzySoft I wasn't aware of Fastlane or Triple-T. It sounds promising ! I'll implement one of them.

Since firebase job dispatcher has been deprecated (it is only the job manager, not analytics) , I might try to find another solution (using https://developer.android.com/topic/libraries/architecture/workmanager/ ? )

Is Bugsnag a real problem ? The source code is available at https://github.com/bugsnag/bugsnag-android

**Comment by IzzySoft** [comment]
Nice thing about Fastlane/Triple-T: both work with Play Store as well in case you plan publishing there. So one place to maintain your metadata, and push them to both. If you don't intend Playstore publishing, you could also simply use the same file structure to place screenshots etc. F-Droid would pick that up then as well.

And yes, I'm aware there are many aspects to Firebase – not only analytics. But AFAIK all of them rely on proprietary components and a non-free network service (Google's), so neither of them is acceptable for F-Droid.

As for Bugsnag, I'm not sure. According to its description, it's a "library that automatically detects crashes in apps, collects diagnostic information and immediately notifies the development team" – which implies Tracking, and doesn't ask the user's consent (further, does it send directly to the dev, or again via their own and probably non-free network service?). If possible, maybe better use e.g. ACRA, where the user decides if an what's being sent?

**Comment by Willena** [comment]
@IzzySoft 
I've implemented Triple-T and it is very very nice. It simplify the publishing process a lot !
I've switched to Workmanager that is part of androidx instead of firebase-jobdispatcher.
Since last version, bugsnag is only activated if the user allows it (during configuration or in the settings).

**Comment by IzzySoft** [comment]
Thanks @Willena! I've asked Pierre whether he could give it a shot – with given corrections.

**Comment by Willena** [comment]
Now that the app is present in:
- [x] GPlay (https://play.google.com/store/apps/details?id=fr.guillaumevillena.opendnsupdater)
- [x] @IzzySoft Repo (https://apt.izzysoft.de/fdroid/index/apk/fr.guillaumevillena.opendnsupdater)
- [x] F-Droid (https://f-droid.org/fr/packages/fr.guillaumevillena.opendnsupdater/)

We can close this issue.

**Comment by IzzySoft** [comment]
Oh, congrats, it's in the official repo! Guess I better remove it from mine then (to avoid confusion with different signatures)? As usual, I'd archive Metadata so re-establishing it would be easy (in case it's needed, e.g. when something gets stuck). What do you say? It's what I usually do at this stage.
