### ISSUE TITLE
Update the design

### ISSUE THREAD

**Issue by Willena** [Willena/OpenDNSUpdater#10]

**Comment by TPS** [comment]
Just FYI: _I_ think your design's just fine, as it closely replicates the official (Windows) program, other than [DNS-o-matic support](https://support.opendns.com/hc/en-us/community/posts/220007087-Using-DNS-O-Matic-with-HTTPS), which I've no idea whether even makes _sense_ on an Android _client_ device.  (Maybe somebody somewhere is running an Android _server_ & will contact re: this support, once #1 is done.)

**Comment by Willena** [comment]
Design wont change a lot now 😄
