### ISSUE TITLE
Add setup and explaination slide for first time use

### ISSUE THREAD

**Issue by Willena** [Willena/OpenDNSUpdater#13]
It was something present on the v1.0 app. 
A setup sequence with explaination on our to use the app and what are the basic features might be very useful.

**Comment by TPS** [comment]
Just updated from GPlay (10 min after receiving notification on this issue from GitHub!) & went through the onboarding screens.  It picked up my existing settings fine, & looked perfectly professional & functional!

Kudos! 👏

**Comment by Willena** [comment]
Now the app start to look like what I had in mind. Compare it that with the 1.0.0 that was published on GitHub before :)
