### ISSUE TITLE
Possibility for the app to become device administrator

### ISSUE THREAD

**Issue by Willena** [Willena/OpenDNSUpdater#17]
Some user would like to see a new features.

They want to be able to set the app as device administrator avoid this app being uninstalled.

**Comment by ojchase** [comment]
+1 This would be very helpful.

**Comment by ojchase** [comment]
@Willena I've reinstalled onto 2.2.4 and can't figure out how to enable device admin. I don't see any options in the UI and (Basic Android) Settings -> Security -> Device admin apps shows other apps I've enabled, but Open DNS Updater isn't an option. How do we enable this?

**Comment by ojchase** [comment]
I'm suspicious that the above commit on the feature/device-admin branch needs to be merged into master.
