### ISSUE TITLE
Whitelist of network

### ISSUE THREAD

**Issue by Willena** [Willena/OpenDNSUpdater#18]
A user requested to add a whitelist to the settings menu. So that it is possible to update only on specific network.

**Comment by Willena** [comment]
Implemented in 060bdbc

**Comment by TPS** [comment]
@Willena I use a local VPN ([Adguard](https://adguard.com/en/adguard-android/overview.html) for adblocking) & I get the following when adding my current wifi to the whitelist.
![Screenshot_20210123-133519! (1).png](https://user-images.githubusercontent.com/185902/105611997-e857c880-5d86-11eb-97db-4ce3bd1e5706.png)
Maybe something you can resolve?
