### ISSUE TITLE
Support other DDNS providers

### ISSUE THREAD

**Issue by dyndn** [Willena/OpenDNSUpdater#21]
There're many DDNS providers using `dyndns2` protocol including https://www.nsupdate.info/ which is recommended by https://prism-break.org/en/all/#dns . OpenDNSUpdater could be changed to a generic `dyndns2` client (or a more generic one like https://github.com/openwrt/packages/tree/master/net/ddns-scripts) allowing users to specify DNS update URL, the change could be in the same area as https://github.com/Willena/OpenDNSUpdater/issues/19

**Comment by Willena** [comment]
Switching to a generic `dyndns2` client is great, I didn't know that something like this existed ! I'll consider that for the next versions.

But on the part where users can change the URL, I don't know if it is a good thing or not. You know, this app is, for now focused on the OpenDNS service only, and I was not planning to add any support for other providers.

**Comment by TPS** [comment]
@Willena Your licensing terms do allow anyone else to fork to do such, so do as _you_ see fit.  If you don't use these other services yourself, I can imagine it'd be tough to develop for them, even if (hint, hint, @dyndn) _someone_ were to submit a PR, because the feature would _still_ have to be maintained.

**Comment by dyndn** [comment]
Currently I only need `dyndns2` for `nsupdate.info` and I have no plan to switch to another provider . I only mentioned custom DNS update URL which is supported by the `ddns-scripts` package from `OpenWrt` is because the package is well-maintained and the user base is probably quite large, I thought it might be possible for this project to use it as a library or copy some of the code which would probably be relatively easy to maintain once it's integrated.

To change this to a generic `dyndns2` client, I can see two options
- make existing `dyndns2` code customizable
- use `ddns-scripts` as a library or reuse some of the code which supports many protocols including `dyndns2`

The first option is easier to develop, the second option may not even be possible, but if it is, there would be more work to do initially, but once it's done, it'd be relatively easy to maintain, and this project could then benefit from future improvement of `ddns-scripts`

**Comment by Willena** [comment]
> @Willena Your licensing terms do allow anyone else to fork to do such, so do as _you_ see fit. If you don't use these other services yourself, I can imagine it'd be tough to develop for them, even if (hint, hint, @dyndn) if someone were to submit a PR, because the feature would _still_ have to be maintained.

To be 100% honest I do not need this app any more for my personal usage but still maintaining it when I've got time. If a PR is made for this improvement I might accept it, contribution are always welcomed. ddns clients and protocols seams to be quite stable so maintaining, might not be that hard to do. It could be a good improvement, but I don't think it will have full priority.

 > I only mentioned custom DNS update URL which is supported by the ddns-scripts package from OpenWrt is because the package is well-maintained and the user base is probably quite large, I thought it might be possible for this project to use it as a library or copy some of the code which would probably be relatively easy to maintain once it's integrated.

The "Real" problem with this code base, is that they use shell script to do the updated. I would have to translate them to Java. I did not look on the internet, but someone might have done a Java ddns client that could be used right away without too much work. 

_(Ref only) perl ddclient : https://github.com/ddclient/ddclient_

**Comment by TPS** [comment]
IfF you can use a (GPL2-licensed) C client example, https://github.com/troglobit/inadyn seems like a multiple-service currently-maintained option.  (IfF you _do_ use it directly, do remember to not just _include_ the binary, but actually have it _built_, for F-droid's sake.)

Else, ifF you want Java per-se, https://github.com/topics/ddns?l=java _might_ give some pointers, but a cursory look didn't show anything as nice as the above.  Even Google doesn't really show any current, that I could find.

**Comment by TPS** [comment]
_N.B.: I updated the above to https://github.com/troglobit/inadyn, as the other seemed tied to specific Arduino boards.  In-a-Dyn seems functional for most Linuxes, so probably closer for Android._

**Comment by TPS** [comment]
Just ran into https://github.com/lbgongfu/MultiDDNS-ANDROID, which reminded me of this. Sadly, it looks like all development has stalled.  I do still use this app, though @Willena no longer does, per above.
