### ISSUE TITLE
about https://android.guillaumevillena.fr/

### ISSUE THREAD

**Issue by ghost** [Willena/OpenDNSUpdater#27]
@Willena 
* I found https://android.guillaumevillena.fr/ in fdroid client app
* it shows **Site not installed**

**Comment by Willena** [comment]
Hello, 

I am still the owner of this website, but never got the time and the motivation to build something interesting with the ideas I had in mind a few years back. 
Do not expect something on this website in the next months (or years...)

**Comment by ghost** [comment]
Hello @Willena again,
* removed WebSite in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13616
* thank you
