### ISSUE TITLE
Detect and notify the user of a bad configuration

### ISSUE THREAD

**Issue by Willena** [Willena/OpenDNSUpdater#8]
Do not forget to ask the user to change the configuration.

https://support.opendns.com/hc/en-us/articles/227986567-How-to-test-for-successful-OpenDNS-configuration- provide some links that can be used to test "how well we are protected" 

Solution
 
     To test if you are using OpenDNS as a DNS resolver, we recommend using the following test site to test: http://welcome.opendns.com. If you are using us you will see: Welcome to OpenDNS!

 

    To test the Security Settings of your configuration, we recommend using the following test site to test blocking the Security setting for Phishing: http://www.internetbadguys.com. The desired outcome is to see: This domain is blocked due to a phishing threat.

 

    To test Content filtering for your configuration, we recommend using the following test site to test blocking pornography sites: http://www.exampleadultsite.com. You should see: This domain is blocked.

**Comment by Willena** [comment]
This page is also use full for testing if we effectively used OpenDNS DNSServers

https://welcome.opendns.com

The page return  the following content if we are not using their servers.

> Oops!
> You aren't using OpenDNS yet. Let's fix that

**Comment by TPS** [comment]
Rather than scraping, is there anything @, e.g., https://github.com/folbricht/umbrella, that could help do this via API?

**Comment by Willena** [comment]
@TPS I've already seen this project but also checked out the Cisco umbrella website. The only thing I can remember is that it sounds like a tool to check if a domain is "malicious" or not. And there is no endpoint to update the IP user. This kind of API is useful in a firewall or something like that.

I do not know if I'm right.
